"use client";

import { useState } from "react";
import ReactMarkdown from "react-markdown";

type PromptKey = "how_so_far" | "how_to_improve";

const PROMPTS: { key: PromptKey; label: string }[] = [
  { key: "how_so_far", label: "How's the measurement so far?" },
  { key: "how_to_improve", label: "How can I improve from here?" },
];

export function AiInsights({
  deviceId,
  disabled,
}: {
  deviceId: string;
  disabled?: boolean;
}) {
  const [busyKey, setBusyKey] = useState<PromptKey | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [responses, setResponses] = useState<Partial<Record<PromptKey, string>>>(
    {}
  );

  async function ask(key: PromptKey) {
    setBusyKey(key);
    setError(null);
    const res = await fetch("/api/ai/summary", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ device_id: deviceId, prompt_key: key, days: 14 }),
    });
    setBusyKey(null);
    if (!res.ok) {
      const j = await res.json().catch(() => ({}));
      setError(typeof j.error === "string" ? j.error : "Request failed.");
      return;
    }
    const j = await res.json();
    setResponses((prev) => ({ ...prev, [key]: j.markdown as string }));
  }

  return (
    <div className="mt-3 space-y-4">
      <div className="flex flex-wrap gap-2">
        {PROMPTS.map((p) => (
          <button
            key={p.key}
            onClick={() => ask(p.key)}
            disabled={disabled || busyKey !== null}
            className="rounded-md border border-brand-600 px-3 py-2 text-sm text-brand-700 hover:bg-brand-50 disabled:opacity-50"
          >
            {busyKey === p.key ? "Thinking…" : p.label}
          </button>
        ))}
      </div>

      {disabled && (
        <p className="text-xs text-slate-500">
          Sync some readings first, then ask for insights.
        </p>
      )}
      {error && <p className="text-sm text-red-600">{error}</p>}

      {PROMPTS.map((p) =>
        responses[p.key] ? (
          <article
            key={p.key}
            className="prose prose-sm max-w-none rounded-md border bg-slate-50 p-4"
          >
            <h3 className="text-sm font-semibold text-slate-700">{p.label}</h3>
            <ReactMarkdown>{responses[p.key]!}</ReactMarkdown>
          </article>
        ) : null
      )}

      <p className="text-xs text-slate-500">
        Insights are generated by Gemini from your recent readings. They are
        general lifestyle information, not medical advice — always consult a
        healthcare professional.
      </p>
    </div>
  );
}
